### ISSUE TITLE
Biber not available for x86_64-linuxmusl

### ISSUE THREAD

**Issue by krumeich** [TeX-Live/texlive-source#10]
I tried installing biber in an Alpine based docker image. However, there is no x86_64-linuxmusl build for biber, only the traditional x86_64-linux, but this doesn't help me with my Alpine image.

Is this an oversight or am I doing something completely wrong? Terribly sorry if this is the wrong place to post. Kindly pointly in the right direction.

Thanks for your consideration!

**Comment by norbusan** [comment]
Biber is special, since the binaries are provided by upstream author and are not build from TeX Live source. I guess there is no other way then asking someone with Alpine experience to build the package. It is not that complicated, but needs lots of Perl modules.
