### ISSUE TITLE
important issues found by covscan in texlive

### ISSUE THREAD

**Issue by ngothan** [TeX-Live/texlive-source#11]
there're important issues found by covscan. The scan-results.err is attached in this report
[scan-results.err.gz](https://github.com/TeX-Live/texlive-source/files/2604672/scan-results.err.gz)

**Comment by kberry** [comment]
thanks for the report. i glanced over a few of these 5800 errors. some are valid, some are valid but don't need to be fixed for whatever reason, some are in code we don't maintain, etc. i and perhaps others can go through it as time permits, so it's not likely anything will happen soon. also, it's not going to be a goal for covscan (never heard of it before now) to run 100% cleanly in TeX Live.

**Comment by kberry** [comment]
i have extracted the reports for some (not yet all) of the elsewhere-maintained programs and sent them to the upstream maintainers: namely autosp, devnag, m-tx, pmx, ps2eps, xpdfopen, dvisvgm, lcdf-typetools. Further updates as time permits ...

**Comment by t-tk** [comment]
Thanks for the report.
I don't know what is covscan. Where can I get it?

**Comment by ngothan** [comment]
More infos about covscan you can have a look at https://scan.coverity.com/faq

**Comment by t-tk** [comment]
Thank you.

**Comment by kberry** [comment]
@t-tk  fwiw, the other developers who have looked at their chunk already are that most of the reports are bogus, but a few real ones may be mixed in. so i wouldn't bother spending too much time on it. whatever jumps out as a real problem or easily checked ...

**Comment by kberry** [comment]
old, closing.
