### ISSUE TITLE
(texlive-mingw) compile xetex.exe only 

### ISSUE THREAD

**Issue by luigiScarso** [TeX-Live/texlive-source#16]
Cross-compiling xetex.exe only doesn't work.

TEXLIVEOPT="--disable-all-pkgs --enable-xetex --disable-native-texlive-build --enable-shared"
$> ./Build  $TEXLIVEOPT --host=x86_64-w64-mingw32 --build=x86_64-unknown-linux-gnu

After I have to switch to texk/web2c and run
$> make xetex.exe

**Comment by norbusan** [comment]
@luigiScarso what should we do here???

**Comment by kberry** [comment]
old, closing.
