### ISSUE TITLE
ConTeXt brocken after texlive-binaries update

### ISSUE THREAD

**Issue by jorgesallum** [TeX-Live/texlive-source#66]
Hi there! 

After Ubuntu machines updated the texlive-binaries lib, the conTeXt compiler  stopped working. I reinstalled TeX Live on a machine with the Manjaro distro and the problem continues to occur. For a test file like `\starttext Hello \stoptext` here is the error message:

```sh
This is LuaTeX, Version 1.14.0 (TeX Live 2022/dev/Debian)
  system commands enabled.

fatal error : unable to load bytecode register 544, maybe wipe the cache first

system | total runtime: 0.224 seconds
```

**Comment by kberry** [comment]
Please contact Ubuntu. We can't guess what might going wrong or what Ubuntu has intended in their ConTeXt setup.
