### ISSUE TITLE
Fix incompatibility with ostree immutable root systems

### ISSUE THREAD

**Issue by tsilvs** [TeX-Live/texlive-source#70]
I stumbled upon an issue with tex templates when tried to fix an error I get when I run `pandoc -i input.md -o output.pdf`.

The logs:

<details>
<summary><code>$>pandoc -i input.md -o output.pdf</code></summary>

```
kpathsea: Running mktexfmt pdflatex.fmt
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /var/home/tsilvs/.texlive2023/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /var/home/tsilvs/.texlive2023/texmf-var/web2c
mktexfmt [INFO]: Did not find entry for byfmt=pdflatex skipped
mktexfmt [INFO]: total formats: 0
mktexfmt [INFO]: exiting with status 0

kpathsea: Running mktexfmt pdflatex.fmt
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /var/home/tsilvs/.texlive2023/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /var/home/tsilvs/.texlive2023/texmf-var/web2c
mktexfmt [INFO]: Did not find entry for byfmt=pdflatex skipped
mktexfmt [INFO]: total formats: 0
mktexfmt [INFO]: exiting with status 0
Error producing PDF.
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Fedora 39) (preloaded format=pdflatex)
 restricted \write18 enabled.
I can't find the format file `pdflatex.fmt'!
```

</details>
<details>
<summary><code>$>rpm-ostree install pandoc-pdf</code></summary>

`error: Package/capability 'pandoc-pdf' is already requested`

</details>
<details>
<summary><code>$>sudo fmtutil-sys --all</code></summary>

```
fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
fmtutil:   /usr/share/texlive/texmf-config/web2c/fmtutil.cnf
fmtutil [INFO]: writing formats under /var/lib/texmf/web2c
fmtutil [WARNING]: You seem to have no formats defined in your fmtutil.cnf files!
fmtutil [INFO]: total formats: 0
fmtutil [INFO]: exiting with status 0
```

</details>
<details>
<summary><code>$>sudo mktexlsr</code></summary>

```
mktexlsr: /usr/share/texlive/texmf-config: directory not writable. Skipping...
mktexlsr: /usr/share/texlive/texmf-dist: directory not writable. Skipping...
mktexlsr: /usr/share/texlive/texmf-local//: directory not writable. Skipping...
mktexlsr: Updating /var/lib/texmf/ls-R... 
mktexlsr: Done.
```

</details>
<details>
<summary><code>$>pandoc -i input.md -o output.pdf</code></summary>

```
kpathsea: Running mktexfmt pdflatex.fmt
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /var/home/tsilvs/.texlive2023/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /var/home/tsilvs/.texlive2023/texmf-var/web2c
mktexfmt [INFO]: Did not find entry for byfmt=pdflatex skipped
mktexfmt [INFO]: total formats: 0
mktexfmt [INFO]: exiting with status 0

kpathsea: Running mktexfmt pdflatex.fmt
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /var/home/tsilvs/.texlive2023/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /var/home/tsilvs/.texlive2023/texmf-var/web2c
mktexfmt [INFO]: Did not find entry for byfmt=pdflatex skipped
mktexfmt [INFO]: total formats: 0
mktexfmt [INFO]: exiting with status 0
Error producing PDF.
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Fedora 39) (preloaded format=pdflatex)
 restricted \write18 enabled.
I can't find the format file `pdflatex.fmt'!
```

</details>

Can we somehow permanently move tex configs & caches to `/etc`?

**Comment by norbusan** [comment]
The problem you are seeing is an incorrect setup by the distributor of
the TeX Live packages for your system.


> mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
> mktexfmt:   /var/home/tsilvs/.texlive2023/texmf-config/web2c/fmtutil.cnf

Formats should be automatically pregenerated in TEXMFSYSVAR
	kpsewhich -var-value TEXMFSYSVAR

> mktexfmt [INFO]: writing formats under /var/home/tsilvs/.texlive2023/texmf-var/web2c
> mktexfmt [INFO]: Did not find entry for byfmt=pdflatex skipped

It seems that your fmtutil.cnf is broken, in addition.

> <summary><code>$>sudo fmtutil-sys --all</code></summary>
> 
> ```
> fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
> fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
> fmtutil:   /usr/share/texlive/texmf-config/web2c/fmtutil.cnf
> fmtutil [INFO]: writing formats under /var/lib/texmf/web2c
> fmtutil [WARNING]: You seem to have no formats defined in your fmtutil.cnf files!
> fmtutil [INFO]: total formats: 0
> fmtutil [INFO]: exiting with status 0
> ```

fmtutil.cnf seems to be broken.

> <summary><code>$>sudo mktexlsr</code></summary>
> 
> ```
> mktexlsr: /usr/share/texlive/texmf-config: directory not writable. Skipping...
> mktexlsr: /usr/share/texlive/texmf-dist: directory not writable. Skipping...
> mktexlsr: /usr/share/texlive/texmf-local//: directory not writable. Skipping...
> mktexlsr: Updating /var/lib/texmf/ls-R... 
> mktexlsr: Done.
> ```

Again, setup broken. If /usr/share/texlive is not writable, then the
ls-R files MUST BE links to ls-R files in writable directories.

Packaging bug.

> Can we somehow permanently move tex configs & caches to `/etc`?

Not our problem. Problem of the packagers of TeX Live.
TeX Live has a complete separate setup, but expects that the directories
where it is are installed are *writable*.
