### ISSUE TITLE
bin release artifacts include broken symlinks (mktexfmt)

### ISSUE THREAD

**Issue by evan-flynn-apexai** [TeX-Live/texlive-source#72]
The [latest release artifacts for linux x86](https://github.com/TeX-Live/texlive-source/releases/download/svn69778/texlive-bin-x86_64-linux.tar.gz) include some symlinks that are broken (`mktexfmt` links to `fmtutils` which links to a file outside of the release artifact).

Could the release artifacts be updated to include valid symlinks?

Happy to help make the changes if someone can point me in the right direction :+1:

**Comment by norbusan** [comment]
Yes, this is to be expected. For a fully working system you need the main `texmf-dist` tree. But that is a few Gb and doesn't fit on github.

**Comment by evan-flynn-apexai** [comment]
@norbusan if they should intentionally be removed, then is there a way to remove them from the release artifact before uploading it to avoid the confusion like I had that maybe they were not supposed to be broken?

`find . -xtype l -delete` right before creating the release artifact should work I think :+1:

**Comment by norbusan** [comment]
Hi @evan-flynn-apexai 
the artifacts are not meant for consumption, it never has been.
Why should they be removed?
We use the binary builds here and incorporate them (the files and link) into our subversion repo that drives the whole infra and packaging.
Removing the links would break a lot of other things.

What is your **use** of these binaries? 

You can drop them into ROOT/texlive/XXX/bin/ARCH/ and it will work automatically, if you have a proper texlive installation.

**Comment by evan-flynn-apexai** [comment]
> if you have a proper texlive installation.

@norbusan this was my confusion. I thought the release artifacts from this repo were "stand alone", but I guess there are some prerequisites to using them.

Thanks! I didn't know :+1:

**Comment by norbusan** [comment]
Hi @evan-flynn-apexai 
yes, they are definitely not stand-alone. For standalone system we would need the whole of the TeX Live subversion repo (or its git mirror), but that is not reasonable to be put in github (not possible).

Creating a working TeX Live systems involves:
- building the "binaries" or getting the artifacts built here
- getting the rest of the subversion repo
- combining them into a working system that works on all supported architecture/operating system combinations

Feel free to reach out any time you need some more information!

**Comment by kberry** [comment]
Is there any way we could add an overall comment on the github Releases page explaining this? It would be painful to add text to every release.

I will add something to the top-level README.md, at least. Thanks for the report, Evan.
