### ISSUE TITLE
mktexlsr.pl not included

### ISSUE THREAD

**Issue by spl** [TeX-Live/texlive-source#9]
I'm curious why `mktexlsr.pl` is not found in this repository (and thus not in the `texlive-20180414-source.tar.xz` release). It's used by `fmtutil.pl` (https://github.com/norbusan/texlive-rewrite/commit/8d9f51798d661a44a605c686f72e2c266dd7cb3f), which means that `fmtutil.pl` is unusable as it is.

I understand that it is available from the Subversion [`Master` directory](https://tug.org/svn/texlive/trunk/Master/texmf-dist/scripts/texlive/mktexlsr.pl), but, since it `fmtutil.pl` is in the `Build` directory, it seems like `mktexlsr.pl` should be, too.

**Comment by norbusan** [comment]
Yeah, maybe mktexlsr.pl should be copied here, too, but then, these repository is only used for building the binaries and sending them to us so that they are included in the Master/bin directory. It does not have any guarantee of completeness, installability, usability by itself.

**Comment by spl** [comment]
@norbusan Thanks for responding. I've been experimenting with TeX Live installation, so all the assumptions made about things are not completely clear to me.

> repository is only used for building the binaries and sending them to us so that they are included in the Master/bin directory. It does not have any guarantee of completeness, installability, usability by itself.

To help me understand, why are `fmtutil.pl`, `updmap.pl`, and all of the (linked) scripts included in the `Build` repository? Those don't seem to be used to build binaries.

**Comment by norbusan** [comment]
Because they are installed into `bin/<ARCH>/`.

`Build/source` is used to create in principle *all* files that will go into `Master/bin/<ARCH>`, and thus there are copies of `fmtutil.pl` etc. OTOH, `mktexlsr.pl` is not installed into `Master/bin/<ARCH>`, so it is not necessary to have it in the source tree.

**Comment by spl** [comment]
Okay, I see. Thanks!
